"""
SRD 目录范围，大章节标题，小章节标题。
SRD page-level section map.
"""

from __future__ import annotations

from typing import Any

# 目录范围，大章节标题，小章节标题。
SECTION_MAP: list[dict[str, Any]] = [
    {
        "page_start": 1,
        "page_end": 4,
        "section": "Front Matter",
        "subsection": None,
        "include_in_rag": False,
    },
    {
        "page_start": 5,
        "page_end": 5,
        "section": "Playing the Game",
        "subsection": "Rhythm of Play",
        "include_in_rag": True,
    },
    {
        "page_start": 6,
        "page_end": 7,
        "section": "Playing the Game",
        "subsection": "D20 Tests",
        "include_in_rag": True,
    },
    {
        "page_start": 8,
        "page_end": 8,
        "section": "Playing the Game",
        "subsection": "Proficiency",
        "include_in_rag": True,
    },
    {
        "page_start": 9,
        "page_end": 9,
        "section": "Playing the Game",
        "subsection": "Actions",
        "include_in_rag": True,
    },
    {
        "page_start": 10,
        "page_end": 10,
        "section": "Playing the Game",
        "subsection": "Social Interaction",
        "include_in_rag": True,
    },
    {
        "page_start": 11,
        "page_end": 11,
        "section": "Playing the Game",
        "subsection": "Exploration",
        "include_in_rag": True,
    },
    {
        "page_start": 12,
        "page_end": 12,
        "section": "Playing the Game",
        "subsection": "Travel",
        "include_in_rag": True,
    },
    {
        "page_start": 13,
        "page_end": 15,
        "section": "Playing the Game",
        "subsection": "Combat",
        "include_in_rag": True,
    },
    {
        "page_start": 16,
        "page_end": 18,
        "section": "Playing the Game",
        "subsection": "Damage and Healing",
        "include_in_rag": True,
    },
    {
        "page_start": 19,
        "page_end": 19,
        "section": "Character Creation",
        "subsection": "Choose a Character Sheet",
        "include_in_rag": True,
    },
    {
        "page_start": 20,
        "page_end": 22,
        "section": "Character Creation",
        "subsection": "Create Your Character",
        "include_in_rag": True,
    },
    {
        "page_start": 23,
        "page_end": 23,
        "section": "Character Creation",
        "subsection": "Level Advancement",
        "include_in_rag": True,
    },
    {
        "page_start": 24,
        "page_end": 25,
        "section": "Character Creation",
        "subsection": "Starting at Higher Levels",
        "include_in_rag": True,
    },
    {
        "page_start": 26,
        "page_end": 27,
        "section": "Character Creation",
        "subsection": "Trinkets",
        "include_in_rag": True,
    },
    {
        "page_start": 28,
        "page_end": 30,
        "section": "Classes",
        "subsection": "Barbarian",
        "include_in_rag": True,
    },
    {
        "page_start": 31,
        "page_end": 32,
        "section": "Classes",
        "subsection": "Bard",
        "include_in_rag": True,
    },
    {
        "page_start": 33,
        "page_end": 35,
        "section": "Classes",
        "subsection": "Bard",
        "include_in_rag": True,
    },
    {
        "page_start": 36,
        "page_end": 40,
        "section": "Classes",
        "subsection": "Cleric",
        "include_in_rag": True,
    },
    {
        "page_start": 41,
        "page_end": 46,
        "section": "Classes",
        "subsection": "Druid",
        "include_in_rag": True,
    },
    {
        "page_start": 47,
        "page_end": 48,
        "section": "Classes",
        "subsection": "Fighter",
        "include_in_rag": True,
    },
    {
        "page_start": 49,
        "page_end": 52,
        "section": "Classes",
        "subsection": "Monk",
        "include_in_rag": True,
    },
    {
        "page_start": 53,
        "page_end": 56,
        "section": "Classes",
        "subsection": "Paladin",
        "include_in_rag": True,
    },
    {
        "page_start": 57,
        "page_end": 60,
        "section": "Classes",
        "subsection": "Ranger",
        "include_in_rag": True,
    },
    {
        "page_start": 61,
        "page_end": 63,
        "section": "Classes",
        "subsection": "Rogue",
        "include_in_rag": True,
    },
    {
        "page_start": 64,
        "page_end": 69,
        "section": "Classes",
        "subsection": "Sorcerer",
        "include_in_rag": True,
    },
    {
        "page_start": 70,
        "page_end": 76,
        "section": "Classes",
        "subsection": "Warlock",
        "include_in_rag": True,
    },
    {
        "page_start": 77,
        "page_end": 82,
        "section": "Classes",
        "subsection": "Wizard",
        "include_in_rag": True,
    },
    {
        "page_start": 83,
        "page_end": 83,
        "section": "Character Origins",
        "subsection": "Character Backgrounds",
        "include_in_rag": True,
    },
    {
        "page_start": 84,
        "page_end": 86,
        "section": "Character Origins",
        "subsection": "Character Species",
        "include_in_rag": True,
    },
    {
        "page_start": 87,
        "page_end": 88,
        "section": "Feats",
        "subsection": "Feat Descriptions",
        "include_in_rag": True,
    },
    {
        "page_start": 89,
        "page_end": 91,
        "section": "Equipment",
        "subsection": "Weapons",
        "include_in_rag": True,
    },
    {
        "page_start": 92,
        "page_end": 92,
        "section": "Equipment",
        "subsection": "Armor",
        "include_in_rag": True,
    },
    {
        "page_start": 93,
        "page_end": 93,
        "section": "Equipment",
        "subsection": "Tools",
        "include_in_rag": True,
    },
    {
        "page_start": 94,
        "page_end": 99,
        "section": "Equipment",
        "subsection": "Adventuring Gear",
        "include_in_rag": True,
    },
    {
        "page_start": 100,
        "page_end": 100,
        "section": "Equipment",
        "subsection": "Mounts and Vehicles",
        "include_in_rag": True,
    },
    {
        "page_start": 101,
        "page_end": 101,
        "section": "Equipment",
        "subsection": "Lifestyle Expenses",
        "include_in_rag": True,
    },
    {
        "page_start": 102,
        "page_end": 102,
        "section": "Equipment",
        "subsection": "Hirelings",
        "include_in_rag": True,
    },
    {
        "page_start": 103,
        "page_end": 103,
        "section": "Equipment",
        "subsection": "Crafting Nonmagical Items",
        "include_in_rag": True,
    },
    {
        "page_start": 104,
        "page_end": 104,
        "section": "Spells",
        "subsection": "Gaining Spells",
        "include_in_rag": True,
    },
    {
        "page_start": 105,
        "page_end": 106,
        "section": "Spells",
        "subsection": "Casting Spells",
        "include_in_rag": True,
    },
    {
        "page_start": 107,
        "page_end": 175,
        "section": "Spells",
        "subsection": "Spell Descriptions",
        "include_in_rag": True,
    },
    {
        "page_start": 176,
        "page_end": 191,
        "section": "Rules Glossary",
        "subsection": None,
        "include_in_rag": True,
    },
    {
        "page_start": 192,
        "page_end": 192,
        "section": "Gameplay Toolbox",
        "subsection": "Travel Pace",
        "include_in_rag": True,
    },
    {
        "page_start": 193,
        "page_end": 194,
        "section": "Gameplay Toolbox",
        "subsection": "Curses and Magical Contagions",
        "include_in_rag": True,
    },
    {
        "page_start": 195,
        "page_end": 196,
        "section": "Gameplay Toolbox",
        "subsection": "Environmental Effects",
        "include_in_rag": True,
    },
    {
        "page_start": 197,
        "page_end": 198,
        "section": "Gameplay Toolbox",
        "subsection": "Poison",
        "include_in_rag": True,
    },
    {
        "page_start": 199,
        "page_end": 201,
        "section": "Gameplay Toolbox",
        "subsection": "Traps",
        "include_in_rag": True,
    },
    {
        "page_start": 202,
        "page_end": 203,
        "section": "Gameplay Toolbox",
        "subsection": "Combat Encounters",
        "include_in_rag": True,
    },
    {
        "page_start": 204,
        "page_end": 204,
        "section": "Magic Items",
        "subsection": "Magic Item Categories",
        "include_in_rag": True,
    },
    {
        "page_start": 205,
        "page_end": 205,
        "section": "Magic Items",
        "subsection": "Magic Item Rarity",
        "include_in_rag": True,
    },
    {
        "page_start": 206,
        "page_end": 206,
        "section": "Magic Items",
        "subsection": "Activating a Magic Item",
        "include_in_rag": True,
    },
    {
        "page_start": 207,
        "page_end": 208,
        "section": "Magic Items",
        "subsection": "Sentient Magic Items",
        "include_in_rag": True,
    },
    {
        "page_start": 209,
        "page_end": 253,
        "section": "Magic Items",
        "subsection": "Magic Items A-Z",
        "include_in_rag": True,
    },
    {
        "page_start": 254,
        "page_end": 254,
        "section": "Monsters",
        "subsection": "Stat Block Overview",
        "include_in_rag": True,
    },
    {
        "page_start": 255,
        "page_end": 257,
        "section": "Monsters",
        "subsection": "Running a Monster",
        "include_in_rag": True,
    },
    {
        "page_start": 258,
        "page_end": 343,
        "section": "Monsters",
        "subsection": "Monsters A-Z",
        "include_in_rag": True,
    },
    {
        "page_start": 344,
        "page_end": 364,
        "section": "Animals",
        "subsection": None,
        "include_in_rag": True,
    },
]
